services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    image: bryan834/teachme_backend_seminari:v1
    container_name: teachme_backend_seminari
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://mongodb:27017/BBDD
    depends_on:
      - mongodb

  frontend:
    image: bryan834/teachme_frontend_seminari:v1
    container_name: teachme_frontend_seminari
    ports:
      - "51139:51139" 
    depends_on:
      - backend

volumes:
  mongodb_data:
    driver: local
